actions: "enqueue, allocate, reclaim"
  configurations:
    - name: ScaleAllocatable
      arguments:
        millicpu: 0.7
        memory: 1.0
  tiers:
    - plugins:
        - name: drf
          # These must be set to true to reproduce fairshare behaviour
          enableHierarchy: true
          enableReclaimable: true
        # node order optimisations: least-used node for example
        - name: nodeorder
        # optimal binpacking for nodes
        - name: binpack
        # Option to add cluster-critical pods
        - name: conformance
