name: Tag Release to https://hub.docker.com/repository/docker/dipanjank/spark-volcano

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Install musl
        run: |
          wget http://musl.libc.org/releases/musl-1.2.1.tar.gz
          tar -xf musl-1.2.1.tar.gz && cd musl-1.2.1
          ./configure
          make && sudo make install

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ./src/github.com/${{ github.repository }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

#      - name: Run verify test
#        run: |
#          make verify
#          make TAG=latest generate-yaml
#          make verify-generated-yaml
#          make unit-test
#        working-directory: ./src/github.com/${{ github.repository }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Release
        run: make TAG=${GITHUB_REF#refs/*/} RELEASE_VER=${GITHUB_REF#refs/*/} CC=/usr/local/musl/bin/musl-gcc release
        working-directory: ./src/github.com/${{ github.repository }}
